class GER_Soldier_EP1;
class Bandit1_DZ : GER_Soldier_EP1 {
	displayName = "$STR_CHAR_2";
	side = 1;
	weapons[] = {"Throw","Put"};
	model = "\dayz\characters\man_bandit";
	portrait = "\Ca\characters_E\data\portraits\ger_soldier_CA";
	magazines[] = {};
	backpack = "";
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
};

class BAF_Soldier_Officer_W;
class Rocket_DZ: BAF_Soldier_Officer_W {
	displayName = "Rocket";
	side = 1;
	weapons[] = {"Throw","Put"};
	backpack = "";
	magazines[] = {};
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
};
class BAF_Soldier_W;
class Soldier1_DZ: BAF_Soldier_W {
	displayName = "Soldier";
	side = 1;
	weapons[] = {"Throw","Put"};
	backpack = "";
	magazines[] = {};
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
};
class BAF_Soldier_SniperH_W;
class Sniper1_DZ: BAF_Soldier_SniperH_W {
	displayName = "Sniper";
	side = 1;
	weapons[] = {"Throw","Put"};
	backpack = "";
	magazines[] = {};
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
};
class BAF_Soldier_L_W;
class Camo1_DZ: BAF_Soldier_L_W {
	displayName = "Survivor";
	side = 1;
	weapons[] = {"Throw","Put"};
	backpack = "";
	magazines[] = {};
	respawnWeapons[] = {"Throw","Put"};
	respawnMagazines[] = {};
	weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
	canHideBodies = 1;
};
class Rocker3;
class Rocker3_DZ : Rocker3 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class INS_Lopotev;
	class INS_Lopotev_DZ : INS_Lopotev {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class Pilot_EP1;
	class Pilot_DZ : Pilot_EP1 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class Citizen3_EP1;
	class Citizen3_DZ : Citizen3_EP1 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class Citizen2_EP1;
	class Citizen2_DZ : Citizen2_EP1 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class CIV_EuroMan02_EP1;
	class CIV_EuroMan02_DZ : CIV_EuroMan02_EP1 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
    class CIV_EuroMan01_EP1;
	class CIV_EuroMan01_DZ : CIV_EuroMan01_EP1 {
		displayName = "Survivor";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
	
	//End Of Zombie Infection New Custom Skins
    class BAF_crewman_DDPM;
	class UmbrellaCorp1_DZ : BAF_crewman_DDPM {
		displayName = "UmbrellaCorp";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
	class BAF_Soldier_L_DDPM; // External class reference
	class UmbrellaCorp2_DZ : BAF_Soldier_L_DDPM {
		displayName = "UmbrellaCorp";
		side = TWest;
		weapons[] = {"Throw", "Put"};
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072;
		canHideBodies = true;
	};
	class GUE_Commander;
	class Camo2_DZ: GUE_Commander {
		displayName = "Commander";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class GUE_Soldier_2;
	class Camo3_DZ: GUE_Soldier_2 {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class GUE_Soldier_AT;
	class Camo4_DZ: GUE_Soldier_AT {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class GUE_Soldier_MG;
	class Camo5_DZ: GUE_Soldier_MG {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	
	class CDF_Soldier_TL;
	class Camo6_DZ: CDF_Soldier_TL {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class Ins_Soldier_GL;
	class Camo7_DZ: Ins_Soldier_GL {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class FR_Rodriguez;
	class Camo8_DZ: FR_Rodriguez {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class FR_Sapper;
	class Camo9_DZ: FR_Sapper {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
		engineer = 0;
	};	
	class MVD_Soldier_Sniper;
	class Camo10_DZ: MVD_Soldier_Sniper {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class RUS_Soldier1;
	class Camo11_DZ: RUS_Soldier1 {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class FR_Cooper;
	class Camo12_DZ: FR_Cooper {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	
	class US_Delta_Force_Marksman_EP1;
	class Camo13_DZ: US_Delta_Force_Marksman_EP1 {
		displayName = "Soldier";
		side = 1;
		weapons[] = {"Throw","Put"};
		canCarryBackPack = 1;
		backpack = "";
		magazines[] = {};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
	};	